//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurantClient.ItemServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItemServiceReference.itemInterface")]
    public interface itemInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/GetItems", ReplyAction="http://tempuri.org/itemInterface/GetItemsResponse")]
        System.Data.DataSet GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/GetItems", ReplyAction="http://tempuri.org/itemInterface/GetItemsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/AddItem", ReplyAction="http://tempuri.org/itemInterface/AddItemResponse")]
        void AddItem(string item_name, int item_price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/AddItem", ReplyAction="http://tempuri.org/itemInterface/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(string item_name, int item_price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/UpdateItem", ReplyAction="http://tempuri.org/itemInterface/UpdateItemResponse")]
        void UpdateItem(int item_id, int item_price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itemInterface/UpdateItem", ReplyAction="http://tempuri.org/itemInterface/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(int item_id, int item_price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface itemInterfaceChannel : restaurantClient.ItemServiceReference.itemInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class itemInterfaceClient : System.ServiceModel.ClientBase<restaurantClient.ItemServiceReference.itemInterface>, restaurantClient.ItemServiceReference.itemInterface {
        
        public itemInterfaceClient() {
        }
        
        public itemInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public itemInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public itemInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public itemInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void AddItem(string item_name, int item_price) {
            base.Channel.AddItem(item_name, item_price);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(string item_name, int item_price) {
            return base.Channel.AddItemAsync(item_name, item_price);
        }
        
        public void UpdateItem(int item_id, int item_price) {
            base.Channel.UpdateItem(item_id, item_price);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(int item_id, int item_price) {
            return base.Channel.UpdateItemAsync(item_id, item_price);
        }
    }
}
