//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurantClient.BillServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillServiceReference.billInterface")]
    public interface billInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/billInterface/AddBill", ReplyAction="http://tempuri.org/billInterface/AddBillResponse")]
        void AddBill(int cust_id, string items, int amount, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/billInterface/AddBill", ReplyAction="http://tempuri.org/billInterface/AddBillResponse")]
        System.Threading.Tasks.Task AddBillAsync(int cust_id, string items, int amount, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/billInterface/GetBills", ReplyAction="http://tempuri.org/billInterface/GetBillsResponse")]
        System.Data.DataSet GetBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/billInterface/GetBills", ReplyAction="http://tempuri.org/billInterface/GetBillsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBillsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface billInterfaceChannel : restaurantClient.BillServiceReference.billInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class billInterfaceClient : System.ServiceModel.ClientBase<restaurantClient.BillServiceReference.billInterface>, restaurantClient.BillServiceReference.billInterface {
        
        public billInterfaceClient() {
        }
        
        public billInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public billInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBill(int cust_id, string items, int amount, System.DateTime date) {
            base.Channel.AddBill(cust_id, items, amount, date);
        }
        
        public System.Threading.Tasks.Task AddBillAsync(int cust_id, string items, int amount, System.DateTime date) {
            return base.Channel.AddBillAsync(cust_id, items, amount, date);
        }
        
        public System.Data.DataSet GetBills() {
            return base.Channel.GetBills();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBillsAsync() {
            return base.Channel.GetBillsAsync();
        }
    }
}
